services:
  db:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: desafio01
      MYSQL_DATABASE: listalivros
    volumes:
      - db_data:/var/lib/mysql
      - ./api/db/script.sql:/docker-entrypoint-initdb.d/script.sql
    ports:
      - "3306:3306"

  api:
    image: node:18-slim
    container_name: node-container
    working_dir: /home/node/app
    restart: always
    volumes:
      - ./api:/home/node/app
    ports:
      - "9001:9001"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: desafio01
    command: >
      sh -c "npm install && node index.js"

  php:
    image: php:8.2-apache
    container_name: php-container
    restart: always
    volumes:
      - ./website:/var/www/html
    ports:
      - "8888:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: desafio01

volumes:
  db_data:
